### ISSUE TITLE
Add a gulp command for local web serving

### ISSUE THREAD

**Issue by yozlet** [usagov/vote-gov#107]
Example from @rogeruiz: https://github.com/rogeruiz/scuttle/blob/master/gulpfile.babel.js#L140-L179

**Comment by rogeruiz** [comment]
The largest win here is that it will greatly improve the development workflow for previewing all language content locally.

**AC**:

- [ ] Run the build command (N) times with all of it's dependencies
- [ ] Have new gulp command for serving the `public/` directory created with the previous step
    - [ ] Watch for file changes, and run the build command (N) times again.
- [ ] Update `README.md` documentation about working with the site locally

**Comment by yozlet** [comment]
Given that we now have a custom `nginx.conf`, we may want to use nginx for local serving too.
