### ISSUE TITLE
Change text for states that register by mail

### ISSUE THREAD

**Issue by megdaly** [usagov/vote-gov#112]
For states that you need to register by mail, change text from requires to allows and add in clarification. 
Ex: Change text "Arkansas requires residents to register by mail." to "Arkansas allows residents to register by mail, not online."

Applicable to Arkansas, Colorado, Florida, Idaho, Maine, Michigan, Mississippi, Missouri, Montana, New Jersey, North Carolina, Ohio, Oklahoma, South Dakota, Tennessee, Texas, Wisconsin.

**Comment by jamesharnett** [comment]
This issue has been resolved and should be closed.
