### ISSUE TITLE
turn EAC PDF into machine-readable data

### ISSUE THREAD

**Issue by jpyuda** [usagov/vote-gov#12]
EAC keeps an election calendar at http://www.eac.gov/voter_resources/election_calendar.aspx - we need to define a data schema for this and then convert the data locked within the PDF into YAML (or similar)

The actual work of creating the yaml file is a micropurchase candidate.

**Comment by micahsaul** [comment]
First draft of a json schema is here:
https://github.com/18F/vote-gov/wiki/JSON-Schema-for-Calendars
