### ISSUE TITLE
Add statement about voter reg deadlines to state pages

### ISSUE THREAD

**Issue by megdaly** [usagov/vote-gov#151]
Need to add this to each state page- ideally it would make sense to be in smaller font below the registration option statement (does not apply to North Dakota, American Samoa, Guam, Northern Mariana Islands, Puerto Rico, or U.S. Virgin Islands): 

To vote in the upcoming general election on November 8, many states have ended or will be ending registrations soon. Check your [state's  registration deadline](https://www.usa.gov/voter-registration-deadlines) and [visit your state election office website](https://www.usa.gov/election-office) for more information. 

@arantxarecio will be adding in the Spanish copy for this here.

**Comment by arantxarecio** [comment]
Hola, here is the Spanish copy:

Muchos estados ya han cerrado o pronto cerrarán los plazos de inscripción para votar en las próximas elecciones del 8 de noviembre. Verifique cuál es la [fecha límite de inscripción para votar en su estado](https://gobierno.usa.gov/fechas-limite-inscripcion-para-votar). Para más información visite el [sitio web de la oficina electoral de su estado (en inglés)](https://www.usa.gov/election-office).

Thank you.
