### ISSUE TITLE
Fix the sitemap files

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#368]
This was from the original QA document. Site Map files are all invalid, per Google Search Console.. Is this completed?

**Comment by ArleneGH** [comment]
YouTrack Ticket: https://gsa-ecas.myjetbrains.com/youtrack/issue/USA-372

**Comment by cwacht** [comment]
I was able to create a custom sitemap.xml template, but it inly got applied to `/es/sitemap.xml` and `/en/sitemap.xml`

I can't seem to find a way to edit the sitemap found at `/sitemap.xml`

**Comment by rayestrada** [comment]
This was resolved as part of ticket VOTE-187 and deployed to production.
