### ISSUE TITLE
Add Crazy Egg Script

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#370]
Running new crazy egg report. Have a new script:

<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0007/9651.js" async="async" ></script>

I've already marked on the state.json file Texas and California and set crazy egg=true.  Can you also please add the script to the English and Spanish home pages.

**Comment by sinchagrenchik** [comment]
The Crazy Egg script is already on both home pages.
