### ISSUE TITLE
Add a back button to state pages

### ISSUE THREAD

**Issue by nicolebrennan** [usagov/vote-gov#374]
We are looking to add a back button or link to state pages. Once the user is on a state page, they need to use the back button in the browser. Not such a big deal, but could be a usability pain for people who need to check more than one state (for family), or those who accidentally click the incorrect state.
Tagging both per Arlene's request!
@cwacht @sinchagrenchik

**Comment by sinchagrenchik** [comment]
@nicolebrennan 
Please take a look.

https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-increase-size-datestamp/register/az/

**Comment by nicolebrennan** [comment]
@sinchagrenchik The back button isn't showing up for me at the link: https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-increase-size-datestamp/register/az/

**Comment by sinchagrenchik** [comment]
@nicolebrennan I didn't do this one yet.  That link was for the #375 font size.  Do you have a mock-up for the back button?

**Comment by nicolebrennan** [comment]
Let's go with something like this, but with the styles updated the match the current fonts/colors/sizes. Please make this link consistent with the rest of the text link size and color that already exist in the design.
http://web.archive.org/web/20181001143418/https://vote.gov/register/az/
![Screen Shot 2020-09-21 at 3 15 59 PM](https://user-images.githubusercontent.com/69985969/93811092-a0c90080-fc1d-11ea-8f80-d8814e06c573.png)

**Comment by sinchagrenchik** [comment]
@nicolebrennan Please take a look.

https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-goback/

**Comment by nicolebrennan** [comment]
@sinchagrenchik Can you please make the link hex #11385B, keep the arrow heavy weight, and make the text of the link regular weight and underlined (text only, not the arrow)?

**Comment by sinchagrenchik** [comment]
@nicolebrennan Please take a look.
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-goback/register/ak/

**Comment by nicolebrennan** [comment]
Looks great @sinchagrenchik ! Thank you! Closing with this comment.
