### ISSUE TITLE
Increase size of date stamp 

### ISSUE THREAD

**Issue by nicolebrennan** [usagov/vote-gov#375]
The date stamp (example:https://staging.vote.gov/register/de/) has a slightly smaller font than the rest of the regular text. Can you make sure the font is the same size as the regular text?

@cwacht @sinchagrenchik

**Comment by sinchagrenchik** [comment]
@nicolebrennan Please take a look.
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-increase-size-datestamp/register/az/

**Comment by nicolebrennan** [comment]
Oh ok - I looked at the reply subject line and did not see the coordinating task completion. Makes sense now!
This looks good, links are same size as regular text. Making this as complete.
