### ISSUE TITLE
Appearance of double drop down

### ISSUE THREAD

**Issue by nicolebrennan** [usagov/vote-gov#376]
In Safari, the "Select your state or territory" drop down arrows show up twice. Can you remove the second set?
<img width="271" alt="Screen Shot 2020-09-18 at 3 35 47 PM" src="https://user-images.githubusercontent.com/69985969/93638068-a8da3380-f9c4-11ea-8cdf-02df5afb97b8.png">

@cwacht @sinchagrenchik

**Comment by cwacht** [comment]
Good catch! We didn't have autoprefixer setup to add browser specific style prefixes.

I pushed a fix on a new branch, but I don't see the build on Federalist yet...

**Comment by cwacht** [comment]
@nicolebrennan

I got it working here:
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/double-drop-down/

Please confirm that looks correct in any browsers that we support. I noticed that it fixes the same issue in Firefox.

I tried to add you as a reviewer in the Pull Request, but your username was not an available option so I put @mariamarrero instead. We may want to look into the GitHub settings about who can review Pull Requests.
