### ISSUE TITLE
Roll over color

### ISSUE THREAD

**Issue by nicolebrennan** [usagov/vote-gov#377]
We are looking to choose a different roll over color for the buttons. The current color changes so little from the regular blue that is there, looking for something with more emphasis. 

I think our dark grey is going to be a lateral move...but let's see if that gives us enough differentiation from the dark blue. Here is the hex: #4b4b4d

@cwacht @sinchagrenchik

**Comment by sinchagrenchik** [comment]
@nicolebrennan Please take a look.

https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/Roll-over-color/

**Comment by nicolebrennan** [comment]
Looks good to me for this iteration. This is a definite improvement over the blue to blue that we had. 
Anything beyond this will require some more looking into accessibility in the change in color (is there enough change from the dark blue to the dark grey). If this colorway doesn't work, I'd next suggest the rollover be a reversed out button- a dark blue outline with a light neutral color fill).
@mariamarrero
