### ISSUE TITLE
Adding another link to state pages

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#390]
The EAC is providing us with links for each state for checking your registration.

Under the Voter Registration Deadlines, we wanted to add:

<H2> How to Check Your Voter Registration 

<p>You can confirm your your voter registration status on %state%'s election website.

**Comment by cwacht** [comment]
@ArleneGH Can you provide a spanish translation?

Also, I am assuming that the links in spanish may need `(en inglés)` and `(seleccione español)` options.

Should it be positioned under the registration deadlines section and above the General Election Date?

**Comment by ArleneGH** [comment]
Morning @lggsa!

Can you please translate:

How to Check Your Voter Registration
You can confirm your voter registration status on %state%'s election website.

@cwacht Yes the placement of the link is good. We will need (en inglés) and (seleccione español) options. Can you make sure the link is "confirm your voter registration status on %states%'s election website."

**Comment by lggsa** [comment]
@ArleneGH below is the translation - thanks!

Cómo comprobar su inscripción de votante
Usted puede verificar su inscripción de votante en el sitio web electoral de %states%'s

**Comment by ArleneGH** [comment]
Thanks Laura! @cwacht can you remove one of the "your" on the English page. There are 2 in the copy I gave you.

**Comment by cwacht** [comment]
Good catch! Fixed it.

**Comment by sinchagrenchik** [comment]
Chris,

Thank you for taking care of this quickly.

Sincha Grenchik

USAGov - “Your Guide to Government Information and Services”

GSA, Technology Transformation Service, TTS Solutions

202-834-6389 (Cell)

**Comment by cwacht** [comment]
@ArleneGH Let me know if you have any questions about adding all the links.

I added one for Alabama in [state-data.json](https://github.com/usagov/vote-gov/blob/confirm-registration/config/gulp/state-data.json) as an example.

The new url field is called `"confirm_registration": "URL"`
The optional fields to use for spanish are:
`"confirm_registration_english_only": "true"` or `"confirm_registration_spanish_selection": "true"`

**Comment by ArleneGH** [comment]
Thank you!
