### ISSUE TITLE
FAQ Missing Content

### ISSUE THREAD

**Issue by cwacht** [usagov/vote-gov#407]
The content in the FAQPage JSON is not matching the page content. including missing dates.
For example,
https://vote.gov/register/tx/
You can see it in the DOM
and.or with help from this google test.
https://search.google.com/test/rich-results?id=kb_Mn6-K1-RiKx71Q4Hetg

**Comment by cwacht** [comment]
I fixed the missing dates:
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/faq-missing-dates/

I can also add the new Confirm Registration section to the FAQ, and I see a few opportunities to clean up the code and make it easier to work on in the future.

**Comment by rayestrada** [comment]
Resolved in #592
