### ISSUE TITLE
Planning for after Election Day (Nov. 4)

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#414]
Hi @sinchagrenchik and @cwacht,

Laura and I are already planning how the content will change after the election Nov. 4.
- The Covid Emergency Box: the text will change to "For official election results go to your state election website." The link will go to the state election home page for every state - yes we need another link :) (English and Spanish)

- Remove "General Election Day [header] General Election Day: Tuesday, November 3, 2020."

- Laura and I will update the state pages to read "21 days before election day" or "10 days before election day" etc.

- Can we create a branch / draft so we can see what it looks like?

CC: @lggsa 

![after-election-NJ](https://user-images.githubusercontent.com/41925071/95880909-03597c00-0d46-11eb-9432-9d761931c896.png)

**Comment by lggsa** [comment]
Spanish translation for 
For official election results go to your state election website.
Vea los resultados oficiales de las elecciones en el sitio web electoral de su estado.

I know it's long but it's the shortest I could come up with and still be clear, it's also slightly different but I think it works.

**Comment by sinchagrenchik** [comment]
Hi,

I will work on it.

Thanks.

Sincha Grenchik

USAGov - “Your Guide to Government Information and Services”

GSA, Technology Transformation Service, TTS Solutions

202-834-6389 (Cell)

**Comment by sinchagrenchik** [comment]
@ArleneGH and @lggsa 

Please take a look.

https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/register/ar/

**Comment by sinchagrenchik** [comment]
@ArleneGH 

Please take a look.
for en ingles
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/es/registrar/ar/

for selecciones espanol
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/es/registrar/co/

**Comment by lggsa** [comment]
Hi @sinchagrenchik, I have revised the text for after the election to read:

Para ver los resultados oficiales de las elecciones visite el sitio web electoral de su estado.

Please make this change in your branch at your convenience. Thanks!

**Comment by sinchagrenchik** [comment]
ok
Sincha Grenchik

USAGov - “Your Guide to Government Information and Services”

GSA, Technology Transformation Service, TTS Solutions

202-834-6389 (Cell)

**Comment by sinchagrenchik** [comment]
@lggsa Please take a look.

https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/es/registrar/ar/

**Comment by lggsa** [comment]
It looks great @sinchagrenchik 

 thank you!

**Comment by ArleneGH** [comment]
The new content is now live https://vote.gov/
