### ISSUE TITLE
Changing Emergency Box to Information Box

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#424]
Hi @sinchagrenchik ,

On your after election branch, can you please change it to the blue information banner instead of the yellow:

https://designsystem.digital.gov/components/alert/

Also we would like the "standard" alert size instead of the "slim" alert so it will have more padding.
<img width="1024" alt="vote" src="https://user-images.githubusercontent.com/41925071/97586973-43209480-19d1-11eb-8445-bfcdcf57f039.png">

**Comment by sinchagrenchik** [comment]
Please take a look.
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/

**Comment by ArleneGH** [comment]
Thanks Sincha! Can you use the "standard" size (which is taller), not the slim size.

**Comment by ArleneGH** [comment]
Also Laura and I would like to keep the font size on the live site; in the branch the font size is a little smaller.

**Comment by nicolebrennan** [comment]
Good morning @sinchagrenchik ! 
**Task:** 
Please add 
1. 1px line #000000 just above the info banner 
2. 1px line #000000 just below the info banner
Reason: To make the info banner stand out more during this election period, especially against the grey government banner.
Thank you!

**Comment by sinchagrenchik** [comment]
Okay.

Sincha Grenchik

USAGov - “Your Guide to Government Information and Services”

GSA, Technology Transformation Service, TTS Solutions

202-834-6389 (Cell)

**Comment by ArleneGH** [comment]
Update @sinchagrenchik - just put the 1px line #000000 just above the info banner; not the bottom of the banner. Let's see how that looks. 

cc: @nicolebrennan

**Comment by ArleneGH** [comment]
Done. Thank you Sincha! https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/register/al/
