### ISSUE TITLE
hp link isn't working in the mail-in page

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#425]
Added the new hp_link to Arkansas (mail in registration page):

https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/register/ar/

The link in the emergency box still goes to the more_info link instead of the hp_link.

**Comment by ArleneGH** [comment]
This is only for Arkansas - all of the other mail in registration pages are fine.

**Comment by sinchagrenchik** [comment]
Please delete the duplicate entry. That will fix the problem.

**Comment by ArleneGH** [comment]
Fixed.
