### ISSUE TITLE
Removing Confirming Registration from North Dakota

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#426]
Hi @sinchagrenchik - North Dakota {https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/register/nd/} doesn't require registration. So can you please remove:

How to Check Your Voter Registration
You can confirm your voter registration status on North Dakota’s election website.

Cómo comprobar su inscripción de votante
Usted puede verificar su inscripción de votante en el sitio web electoral de North Dakota (en inglés).

Thanks.

cc: @lggsa

**Comment by sinchagrenchik** [comment]
Hi Arlene,

I am off today and tomorrow, but I will make the changes when I get back
from the pharmacy.

Sincha Grenchik

USAGov - “Your Guide to Government Information and Services”

GSA, Technology Transformation Service, TTS Solutions

202-834-6389 (Cell)

**Comment by ArleneGH** [comment]
Sounds good. Thanks Sincha!

**Comment by sinchagrenchik** [comment]
Hi Arlene,

Please check. https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/sg-after-election/register/nd/

**Comment by ArleneGH** [comment]
Hi Sincha, 

Looks good! Thanks for working on this.
