### ISSUE TITLE
EAC has a new logo

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#442]
Can you please replace the EAC logo in the footer?
Thank you! 
![eac_logo_with_text](https://user-images.githubusercontent.com/41925071/116720960-c59f0680-a9aa-11eb-8b11-2a04519d554b.jpg)

**Comment by ArleneGH** [comment]
If you need to size it down, maybe ask Nicole to do it?

**Comment by sinchagrenchik** [comment]
ok

**Comment by nicolebrennan** [comment]
What size do you need? Are you look for something pixels x pixels, and under a certain KB limit?

**Comment by sinchagrenchik** [comment]
Nicole,

I do not need to adjust the size.  I downloaded an SVG image from the EAC website and used that one instead.
Thanks

Arlene,

Can you take a look and approve it?
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/new-EAC-logo/
https://cg-9e8debaf-b030-4825-a43c-cb2bc850c96c.app.cloud.gov/preview/usagov/vote-gov/new-EAC-logo/es/

Thanks

**Comment by lggsa** [comment]
Arlene is on leave today, I approved your pull request.

**Comment by sinchagrenchik** [comment]
Thank you.

**Comment by rayestrada** [comment]
EAC logo has been removed as part of the Footer contact identifier USWDS refresh in #566
