### ISSUE TITLE
Changing the info on Iowa Pages

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#448]
Hi,

I am changing the content on the Iowa page from 11 days to 15 days. I don't quite remember the order of how it goes into GitHub.

@sinchagrenchik Can you please go ahead and move it to staging; then to master? If I need to edit anything I can do a new pull request. Thanks!

**Comment by rayestrada** [comment]
This was already resolved https://vote.gov/register/ia/. Closing.
