### ISSUE TITLE
Removing "Other Ways to Register to Vote" on Wyoming page

### ISSUE THREAD

**Issue by ArleneGH** [usagov/vote-gov#451]
Hi,

I got an email from Jennifer Martinez of Wyoming's Secretary of State's office. The National Voter Registration form is NOT accepted in Wyoming. They only accept their state online registration form.

Is there a way to remove the "Other Ways to Register to Vote" section from the Wyoming English and Spanish pages?

https://vote.gov/register/wy/
https://vote.gov/es/registrar/wy/

**Comment by rayestrada** [comment]
This was already resolved https://vote.gov/register/wy/. Closing.
