### ISSUE TITLE
typeahead to select state

### ISSUE THREAD

**Issue by jpyuda** [usagov/vote-gov#47]
use a typeahead instead of a select for determining state

**Comment by rogeruiz** [comment]
Going to be using Twitter's `typeahead` and `Bloodhound` libraries to get this done.

Examples here:
https://twitter.github.io/typeahead.js/examples/

**Comment by djeraseit** [comment]
I think Typeahead and Bloodhound are overkill. Autocomplete is an HTML 5 form attribute for input fields. Even better would be to lookup the State by using MaxMind IP database and prefill the input.

If a person does not know how to spell their state's name then they shouldn't be allowed to vote.
