### ISSUE TITLE
test typeahead vs. select

### ISSUE THREAD

**Issue by jpyuda** [usagov/vote-gov#48]
possibly usability testing, possibly a/b testing

**Comment by rogeruiz** [comment]
Related to working on #47.

**Comment by djeraseit** [comment]
Typeahead is optimal and works great on mobile devices; however, I wonder how many people hit the back button and select a different state? Analytics can tell the truth. If peopleu are looking up information for multiple states then a multiple select/tag input should be used.

Lastly, using A/B testing as mentioned by @jpyuda, would allow to see which method is faster (i.e. page time for each type of input).
