### ISSUE TITLE
Regular expression denial of service in glob-parent

### ISSUE THREAD

**Issue by imhunterand** [usagov/vote-gov#577]
This affects the package glob-parent before 5.1.2. The enclosure regex used to check for strings ending in enclosure containing path separator.

on glob-parent in [package-lock.json](https://github.com/usagov/vote-gov/blob/-/package-lock.json).
Or, manually upgrade glob-parent to version 5.1.2 or later. For example:
```json
"dependencies": {
  "glob-parent": ">=5.1.2"
}
```
```json
"devDependencies": {
  "glob-parent": ">=5.1.2"
}
```

**Comment by rayestrada** [comment]
This package is a development dependency requirement and will be updated as future updates become available.

**Comment by imhunterand** [comment]
Hi! @rayestrada 
Today is there an update on this report, regarding bounty appreciated programs policies.

can I resubmit this issue into get **appreciated bounty** to https://hackerone.com/gsa_bbp ``your-programs``
