### ISSUE TITLE
Developer documentation for multi-lingual support

### ISSUE THREAD

**Issue by rogeruiz** [usagov/vote-gov#62]
There needs to be some documentation of an updated CircleCI multi-lingual site deployment and what commands can be run to build, preview, and edit the multi-lingual site. 
### Acceptance Criteria
- [x] How to leverage `npm run *` scripts to build the site
- [ ] Document limitations of local development with the site
- [ ] _Possibly_, leverage another tool to preview the _"deployed"_ combined multi-lingual site.

**Comment by djeraseit** [comment]
I think multi-language should be implemented programatically -- not statically. Using whatever framework and or classes available to whatever language the site is written in to come to life.

Language clues should be gathered from browser headers, IP, etc. And translation should be done on a string, word, or API basis based on Google's current standards for muli-language websites.
