### ISSUE TITLE
disclaimers for data sources

### ISSUE THREAD

**Issue by jpyuda** [usagov/vote-gov#72]
We need to proactively write plain-language disclaimers about where we've gotten the content we're providing and where/how people can verify it. They need to convey:
- Our data source(s)
- That every effort has been put forth to verify the information
- That the ultimate source of truth for information about voting is the state or local election office (depending on context) and that users might want to validate the information there.

**Comment by kategarklavs** [comment]
Working on this now! I currently have one general disclaimer; am also going to write a set of shorter disclaimers.

**Comment by kategarklavs** [comment]
Here's the first draft of disclaimer text:

https://docs.google.com/a/gsa.gov/document/d/1N8_YxeXDNfdOurK5wM5xOVuKVc3COhIeV4-bykNyjRs/edit?usp=sharing

A few questions:

1) Does the tone feel serious enough to you all? (I want these to simultaneously feel aligned with the rest of our content, but be a smidge more serious in tone, due to the subject matter).

2)  Do we need to include any other information in these disclaimers, or are they good as-is?

**Comment by jpyuda** [comment]
Strong work. I think I prefer the single disclaimer, although that may depend on exactly where/how we fit these into the designs (cc: @ericadeahl).

@megdaly any thoughts? Do you think we should bring these into the site as soon as they're applicable, or do you think we're better off waiting until told we need one?

**Comment by kategarklavs** [comment]
I'm also partial to the single disclaimer, but am happy to follow whichever direction the team feels is best.

**Comment by megdaly** [comment]
Looks great and the tone is serious enough. I prefer the single disclaimer too, since it's more general and allows us to work it into the designs a bit easier.  

Let's work the disclaimers into the site as soon as they're applicable rather than waiting.

**Comment by kategarklavs** [comment]
@megdaly and @jpyuda Thanks for your feedback -- I just incorporated it. The only outstanding potential change is regarding whether we can use the Google civic API, or whether we'll be relying on state sites (I left the comment open in the document as a reminder).

**Comment by ericadeahl** [comment]
@kategarklavs @megdaly @jpyuda A few thoughts on where this could go. Let me know what you think / if you have other ideas.

1. Add to the bottom of pages with info (state voting guide, polling place info, registration info):
<img width="1022" alt="screen shot 2016-06-10 at 4 21 35 pm" src="https://cloud.githubusercontent.com/assets/5911280/15981534/b697132a-2f2b-11e6-810f-8b1795f89955.png">


2. Add to the footer (I shortened this version):
<img width="1024" alt="screen shot 2016-06-10 at 4 45 22 pm" src="https://cloud.githubusercontent.com/assets/5911280/15981529/ae414eb6-2f2b-11e6-91f6-2d727034c1da.png">

3. Add to the footer as an expandable link:
<img width="1023" alt="screen shot 2016-06-10 at 4 51 26 pm" src="https://cloud.githubusercontent.com/assets/5911280/15981528/ab00be44-2f2b-11e6-8548-45539dffa2d6.png">

**Comment by kategarklavs** [comment]
@ericadeahl Hey! Personally, I prefer the third option — I'm a fan of keeping this info in its compactest state until folks want to view it. After that, I prefer the second option (more concise!).

**Comment by megdaly** [comment]
I agree with Kate. It's better to have it as expandable in the footer. That way people can read it as needed, but not clutter up the page.
