### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by steluhidalgo** [usagov/vote-gov#812]

**Comment by razznblue** [comment]
Hello! @steluhidalgo  I can help with the Portuguese translations since I speak the language. I'll research on what updates need to be made but any help you could give would be much appreciated! Thanks!

**Comment by razznblue** [comment]
It seems you have a language code for each language
en = english
tl = tagalog

Do you already have one in mind for Portguese?
I was thinking: `pg`?

Also, is there going to be a separate language for Brazilian vs European portuguese or should be they combined into one?

I see quite a few places we would need to update to implement a new language. I can submit a pull request of some initial work on my part. Who should I tag as a reviewer so they can make sure my updates align with what your project needs?

**Comment by steluhidalgo** [comment]
“Hi @razznblue! Thanks so much for your interest and offer to help with the Portuguese translation and coding of this language for Vote.gov. We currently have dedicated teams of translators and developers working on these tasks, and we are not seeking any additional support at this time. We're in the process of developing Volunteer Contribution Guidelines, which we'll post on GitHub soon."

**Comment by razznblue** [comment]
Understood. Thanks for your reply! 
Here is a [link](https://github.com/usagov/vote-gov/pull/823) the PR that I started. 
Whoever will be working on this, can use it as a base to start on. Thanks.

**Comment by rayestrada** [comment]
Released with #831
