### ISSUE TITLE
Add a button or design element saying "Contact us if you need help or have a suggestion."

### ISSUE THREAD

**Issue by jwbowers** [usagov/vote-gov#84]
I noticed that usa.gov already has capability for this at https://www.usa.gov/contact, and in informal discussions about the site and government websites in general, I've heard requests for such a feature. Tagging @jpyuda @megdaly in case this is the wrong place to add such an idea and/or some obvious reason to close this issue immediately.

**Comment by arantxarecio** [comment]
Yes, we recently reviewed the language for this in both English and Spanish. Currently displayed at the top left on the sites.

**Comment by megdaly** [comment]
That's a recent addition to USAgov and it's a good suggestion for vote. If we decide to add, I'll coordinate with the USAgov contact center on it, so they are aware of it and can expect calls, chats and emails.

**Comment by jwbowers** [comment]
Great. I just looked at usa.gov and it looks nice. On the vote site it is worth using it to collect suggestions too? Or better to just leave it as is but integrate it with the vote.gov site if it also makes sense to the rest of the team?
