### ISSUE TITLE
Correct language codes 

### ISSUE THREAD

**Issue by megdaly** [usagov/vote-gov#91]
Below issue was sent in to general USAgov email:

I was looking at vote.usa.gov and want to report incorrect language codes. You list "(Other Languages: CHN, JPN, KOR, ESP, TGL, NAM)".

The standard codes for Chinese, Spanish, and Vietnamese are:
Chinese: "chi" or "zho"  (two-letter "zh")
Spanish: "spa" (two-letter "es")
Vietnamese: "vie" (two-letter "vi")
The one that is particularly strange is "NAM" as that is neither correct nor intuitive.

We need to decide if using ISO 639-1 or ISO 639-2. We've typically used the 2 character codes, ISO 639-1, so I vote for that.

**Comment by jonivy** [comment]
I'd recommend going beyond two characters if feasible.  In Chinese, for example, the two scripts would be zh-Hans and zh-Hant for Traditional Chinese and Simplified Chinese respectively. Being specific can help automated search engine processes as well as browser display.

Jon Ivy, Language & Accessibility Coordinator
CA Secretary of State, Elections Division
