### ISSUE TITLE
Prepare to randomize calls to action.

### ISSUE THREAD

**Issue by jwbowers** [usagov/vote-gov#92]
We now have about 10 proposed calls to action, each of which represents one hunch (mostly backed by research) about how to encourage people to take some action. The vote.gov website offers us an opportunity to learn about these ideas, and to apply them more broadly in the government (for example, in the Web Design Standards). The calls are here https://docs.google.com/document/d/1PU4UgSAlEWXgDZPs2DsGm2r_qTbO-U2GiULaKMyBCbg/edit 

The action to complete this card is to have the site be ready for testing these different calls to action against one another on the live site. Perhaps using optimizely or google analytics to collect the data and/or organize the randomization of the experiment.

**Comment by jamesharnett** [comment]
@jwbowers: Can you set the document to default to "view only" permissions?
