### ISSUE TITLE
Add a module which allows allows users to ask to be reminded about election day (or other important dates)

### ISSUE THREAD

**Issue by jwbowers** [usagov/vote-gov#93]
USA.gov already has an email list service (http://connect.usa.gov/subscribe). We  think that our team can have an impact on civic engagement by enabling people to ask for reminders, and then to send reminders about federal election deadlines. For now, we may just email them around the November election, but eventually people who ask for reminders might be able to request more locally relevant reminders as well. So, this card proposes that we add a module (like the existing modules of "find your polling place", "check your registration status", etc..) for "Email me to remind me to vote." or "Don't let me forget to vote." etc.. that would link to a special email list under the rubric of the usa.gov email lists. 

Learning how to get people to want reminders to do things that they know that they want to do will also help us in the broader FFD project. (this is called narrowing the gap between intention (saying you want to do something, like exercising, etc..) and action (actually doing what you say and believe you really want to do)).

**Comment by arantxarecio** [comment]
Thanks Jake. I know this was brought up before and it's definitely a good
idea. GobiernoUSA.gov has the same email list service (
http://conectate.gobiernousa.gov/suscripciones) so it can work great for
both languages.

We can work out a standard message in both languages for those interested
in receiving this kind of alerts. The USAGov contact center is a good
source of information as well to learn what people want, how often, and how
they want it.

Thanks again.


Arantxa Piperova

USAGov <https://www.usa.gov/explore/>, OCSIT/18F

U.S. General Services Administration

(202) 501-0527
